print "test exit error"
raise Exception("aa")